DROP TABLE IF EXISTS stat CASCADE;

CREATE TABLE IF NOT EXISTS stat (
id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
app varchar(128)                                    NOT NULL,
uri varchar(128)                                    NOT NULL,
ip varchar(16)                                      NOT NULL,
created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);